
spring:
  # database
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.1.20:3307/TestDB?serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
    username: tester
    password: Tester123!@#

logging:
    config: classpath:logback.xml
